## NOTE: if anything is added here the Config class must be updated accordingly

# settings
verbose: True

# input
geo_file: "Geometries/naca0012_100.dat"
chord: 0.1 # m (reference length)
ref_position: [0, 0] # x(m), y(m)

# flow conditions
M_inf: 0.10
T_inf: 20 # deg C
rho_inf: 1.226 # kg/m^3
mu_inf: 1.81e-5
p_inf: 101325 # Pa

# geometry conditions
alpha: 10 # deg

# solver
control_point_offset: 1.0e-7 # m (for numerical stability) ( < 1e-5 )

# wake


# turbulence/viscous


# flow properties
pressure_calculation: "inviscid_bernoulli"

# visualisation
visualisation: True
scale: 'auto'

# output
write_to_file: False

###### checking elementary flows 
# - set geo_file to "Geometries/test_flows.dat"
# - set M_inf to 0
# - set strengths to (in solve): self.source_strengths = np.array([1]) ############