## NOTE: if anything is added here the Config class must be updated accordingly

# settings
verbose: True

# input
geo_file: "Geometries/naca0012_20.dat"
chord: 0.1 # m (reference length)
ref_position: [0, 0] # x(m), y(m)

# flow conditions
M_inf: 0.1
T_inf: 20 # deg C
rho_inf: 1.226 # kg/m^3
mu_inf: 1.81e-5
p_inf: 101325 # Pa

# geometry conditions
alpha: 6 # deg

# solver
control_point_offset: 1.0e-7 # m (for numerical stability) ( < 1e-5 )
convergence_criterion: 0 # 0: single iteration. else: num for change in coeffs (suggest: 1e-2?)

# turbulence/viscous
inflation_layers: 10
wake_starting_index: -1 # 0 for start, -1 for end
wake_points: 10 # number of points in wake
wake_length: 0.02 # m

# flow properties
pressure_calculation: "inviscid_bernoulli"

# visualisation
visualisation: True
scale: 'auto'

# output
output:
  write_to_file: False
  coefficients: 'coefficients.txt'